apiVersion: v1
kind: Service
metadata:
  name: cloudiod-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cloudiod
  ports:
    - name: http
      port: 80 #the service is listening
      targetPort: 8000 #pods are actually listening
      nodePort: 31000
      protocol: TCP

