apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudiod-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudiod
  replicas: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudiod
    spec:
      containers:
        - name: cloudiod
          image: shihyihuang/cloudiod:5.3
          ports:
          - containerPort: 8000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"